# ЛР-04: Ремонтные бригады по единицам техники

## Student notebook: military 01

Это рабочая тетрадь студента для самостоятельного решения.

Готовых численных ответов здесь нет: вы проходите весь учебный маршрут и фиксируете результаты по шагам.

## 1. Контекст и цель

Нужно назначить ремонтные бригады на повреждённые машины с минимальным временем восстановления готовности.

Цель: получить корректное взаимно-однозначное назначение с минимальным суммарным критерием.

## 2. Исходные данные

Критерий оптимизации: **время ремонта, часы** (минимизация).

| Исполнитель \ Задача | БТР-1 | БТР-2 | БМП-1 | БМП-2 |
| --- | --- | --- | --- | --- |
| Рембригада 1 | 14 | 11 | 13 | 12 |
| Рембригада 2 | 12 | 10 | 15 | 11 |
| Рембригада 3 | 11 | 13 | 10 | 14 |
| Рембригада 4 | 13 | 12 | 11 | 10 |

## 3. Мини-пример 3x3 вручную

Перед запуском метод решения сделайте короткую ручную проверку на подматрице 3x3.

| Исполнитель \ Задача | БТР-1 | БТР-2 | БМП-1 |
| --- | --- | --- | --- |
| Рембригада 1 | 14 | 11 | 13 |
| Рембригада 2 | 12 | 10 | 15 |
| Рембригада 3 | 11 | 13 | 10 |

Что сделать:
1. Предложите вручную взаимно-однозначное назначение для 3 исполнителей и 3 задач.
2. Посчитайте суммарный критерий вручную.
3. Сравните с результатом метод решения после выполнения кода.

## 4. Пошаговое задание

1. Подготовьте входные данные (`worker_names`, `task_names`, `cost_matrix`).
2. Решите задачу через `linear_sum_assignment`.
3. Соберите таблицу `assignment_df` с колонками `исполнитель`, `задача`, `затраты`.
4. Посчитайте `total_cost`.
5. Проверьте «один к одному» ограничения через `assert`.
6. Дайте короткую интерпретацию результата в прикладных терминах.

In [1]:
import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment

worker_names = ['Рембригада 1', 'Рембригада 2', 'Рембригада 3', 'Рембригада 4']
task_names = ['БТР-1', 'БТР-2', 'БМП-1', 'БМП-2']
cost_matrix = np.array([[14, 11, 13, 12], [12, 10, 15, 11], [11, 13, 10, 14], [13, 12, 11, 10]], dtype=float)

print('Размер матрицы:', cost_matrix.shape)
print('Исполнителей:', len(worker_names))
print('Задач:', len(task_names))

Размер матрицы: (4, 4)
Исполнителей: 4
Задач: 4

## 5. Шаблон самостоятельного решения

Заполните блоки с пометкой «Задание». После заполнения код должен вывести итоговую таблицу и пройти проверки `assert`.

In [2]:
# Задание 1: получите оптимальное назначение методом Венгера.
row_ind, col_ind = linear_sum_assignment(cost_matrix)

# Задание 2: вычислите суммарный критерий.
total_cost = float(cost_matrix[row_ind, col_ind].sum())

# Задание 3: соберите таблицу assignment_df с фиксированными колонками.
assignment_rows = []
for i, j in zip(row_ind, col_ind):
    assignment_rows.append({
        'исполнитель': worker_names[i],
        'задача': task_names[j],
        'затраты': float(cost_matrix[i, j]),
    })
assignment_df = pd.DataFrame(assignment_rows, columns=['исполнитель', 'задача', 'затраты'])

# Задание 4: включите проверки «один к одному» ограничений.
assert len(row_ind) == len(worker_names), 'Назначены не все исполнители.'
assert len(col_ind) == len(task_names), 'Назначены не все задачи.'
assert len(set(row_ind)) == len(worker_names), 'Исполнитель повторяется более одного раза.'
assert len(set(col_ind)) == len(task_names), 'Задача назначена более одного раза.'
assert assignment_df['исполнитель'].nunique() == len(worker_names), 'Дубликаты исполнителей в таблице.'
assert assignment_df['задача'].nunique() == len(task_names), 'Дубликаты задач в таблице.'

print("\n=== ОПТИМАЛЬНОЕ НАЗНАЧЕНИЕ ===\n")
display(assignment_df)
print('Суммарный критерий (общее время ремонта):', total_cost, 'часов')

print("\n=== ПРОВЕРКА ОГРАНИЧЕНИЙ ===\n")
print("✓ Все ремонтные бригады назначены")
print("✓ Все единицы техники распределены")
print("✓ Нет повторяющихся назначений")
print("✓ Взаимно-однозначное соответствие соблюдено")

=== ОПТИМАЛЬНОЕ НАЗНАЧЕНИЕ ===

    исполнитель задача  затраты
0  Рембригада 1  БТР-2     11.0
1  Рембригада 2  БТР-1     12.0
2  Рембригада 3  БМП-1     10.0
3  Рембригада 4  БМП-2     10.0

Суммарный критерий (общее время ремонта): 43.0 часов

=== ПРОВЕРКА ОГРАНИЧЕНИЙ ===

✓ Все ремонтные бригады назначены
✓ Все единицы техники распределены
✓ Нет повторяющихся назначений
✓ Взаимно-однозначное соответствие соблюдено

In [3]:
print("\n=== ДЕТАЛЬНЫЙ АНАЛИЗ НАЗНАЧЕНИЙ ===\n")

# Сортируем назначения по времени
assignment_sorted = assignment_df.sort_values('затраты')
print("Назначения по возрастанию времени ремонта:")
display(assignment_sorted)

print("\nСтатистика по назначениям:")
print(f"Минимальное время ремонта: {assignment_sorted['затраты'].min():.0f} ч")
print(f"Максимальное время ремонта: {assignment_sorted['затраты'].max():.0f} ч")
print(f"Среднее время ремонта: {assignment_sorted['затраты'].mean():.2f} ч")
print(f"Общее время ремонта: {assignment_sorted['затраты'].sum():.0f} ч")

print("\nСравнение с альтернативными вариантами:")
# Альтернативное назначение (диагональное)
alternative_cost = sum(cost_matrix[i][i] for i in range(4))
print(f"Диагональное назначение: {alternative_cost:.0f} ч")
print(f"Оптимальное назначение: {total_cost:.0f} ч")
print(f"Экономия времени: {alternative_cost - total_cost:.0f} ч ({((alternative_cost - total_cost)/alternative_cost*100):.1f}%)")

=== ДЕТАЛЬНЫЙ АНАЛИЗ НАЗНАЧЕНИЙ ===

Назначения по возрастанию времени ремонта:

    исполнитель задача  затраты
3  Рембригада 4  БМП-2     10.0
2  Рембригада 3  БМП-1     10.0
0  Рембригада 1  БТР-2     11.0
1  Рембригада 2  БТР-1     12.0

Статистика по назначениям:
Минимальное время ремонта: 10 ч
Максимальное время ремонта: 12 ч
Среднее время ремонта: 10.75 ч
Общее время ремонта: 43 ч

Сравнение с альтернативными вариантами:
Диагональное назначение: 44 ч
Оптимальное назначение: 43 ч
Экономия времени: 1 ч (2.3%)

In [4]:
print("\n=== МИНИ-ПРИМЕР 3x3 (РУЧНАЯ ПРОВЕРКА) ===\n")

# Подматрица 3x3
mini_workers = ['Рембригада 1', 'Рембригада 2', 'Рембригада 3']
mini_tasks = ['БТР-1', 'БТР-2', 'БМП-1']
mini_cost = np.array([
    [14, 11, 13],
    [12, 10, 15],
    [11, 13, 10]
], dtype=float)

print("Матрица времени ремонта 3x3:")
mini_cost_df = pd.DataFrame(mini_cost, index=mini_workers, columns=mini_tasks)
display(mini_cost_df)

# Ручное решение для 3x3
print("\nРучной анализ возможных назначений:")
print("\nВариант 1: Рембригада 1→БТР-2 (11), Рембригада 2→БТР-1 (12), Рембригада 3→БМП-1 (10)")
cost1 = 11 + 12 + 10
print(f"  Суммарное время: {cost1} ч")

print("\nВариант 2: Рембригада 1→БТР-1 (14), Рембригада 2→БТР-2 (10), Рембригада 3→БМП-1 (10)")
cost2 = 14 + 10 + 10
print(f"  Суммарное время: {cost2} ч")

print("\nВариант 3: Рембригада 1→БТР-2 (11), Рембригада 2→БМП-1 (15), Рембригада 3→БТР-1 (11)")
cost3 = 11 + 15 + 11
print(f"  Суммарное время: {cost3} ч")

print("\nВариант 4: Рембригада 1→БМП-1 (13), Рембригада 2→БТР-1 (12), Рембригада 3→БТР-2 (13)")
cost4 = 13 + 12 + 13
print(f"  Суммарное время: {cost4} ч")

# Оптимальное решение для 3x3 через Венгерский алгоритм
mini_row, mini_col = linear_sum_assignment(mini_cost)
mini_cost_opt = mini_cost[mini_row, mini_col].sum()

print(f"\nОптимальное решение (Венгерский алгоритм): {mini_cost_opt:.0f} ч")
print(f"Минимальное найденное вручную: {min(cost1, cost2, cost3, cost4)} ч")

# Сравнение
if mini_cost_opt == min(cost1, cost2, cost3, cost4):
    print("✓ Ручная проверка подтверждает оптимальность!")
else:
    print("⚠ Ручной расчет требует уточнения")

print("\nОптимальное назначение для 3x3:")
mini_assignments = []
for i, j in zip(mini_row, mini_col):
    mini_assignments.append({
        'исполнитель': mini_workers[i],
        'задача': mini_tasks[j],
        'затраты': float(mini_cost[i, j])
    })
mini_df = pd.DataFrame(mini_assignments)
display(mini_df)

=== МИНИ-ПРИМЕР 3x3 (РУЧНАЯ ПРОВЕРКА) ===

Матрица времени ремонта 3x3:

              БТР-1  БТР-2  БМП-1
Рембригада 1   14.0   11.0   13.0
Рембригада 2   12.0   10.0   15.0
Рембригада 3   11.0   13.0   10.0

Ручной анализ возможных назначений:

Вариант 1: Рембригада 1→БТР-2 (11), Рембригада 2→БТР-1 (12), Рембригада 3→БМП-1 (10)
  Суммарное время: 33 ч

Вариант 2: Рембригада 1→БТР-1 (14), Рембригада 2→БТР-2 (10), Рембригада 3→БМП-1 (10)
  Суммарное время: 34 ч

Вариант 3: Рембригада 1→БТР-2 (11), Рембригада 2→БМП-1 (15), Рембригада 3→БТР-1 (11)
  Суммарное время: 37 ч

Вариант 4: Рембригада 1→БМП-1 (13), Рембригада 2→БТР-1 (12), Рембригада 3→БТР-2 (13)
  Суммарное время: 38 ч

Оптимальное решение (Венгерский алгоритм): 33 ч
Минимальное найденное вручную: 33 ч
✓ Ручная проверка подтверждает оптимальность!

Оптимальное назначение для 3x3:

    исполнитель задача  затраты
0  Рембригада 1  БТР-2     11.0
1  Рембригада 2  БТР-1     12.0
2  Рембригада 3  БМП-1     10.0

In [5]:
print("\n=== ИНТЕРПРЕТАЦИЯ РЕЗУЛЬТАТОВ ===\n")

print("1. Оптимальное распределение ремонтных бригад по единицам техники:")
for _, row in assignment_df.iterrows():
    print(f"   • {row['исполнитель']} → {row['задача']} (время ремонта: {row['затраты']:.0f} ч)")

print(f"\n2. Общее время восстановления готовности: {total_cost:.0f} часов")

print("\n3. Анализ эффективности:")
# Сравниваем с худшим возможным назначением
worst_cost = 0
for i in range(4):
    worst_cost += max(cost_matrix[i])
print(f"   • Лучшее (оптимальное) время: {total_cost:.0f} ч")
print(f"   • Худшее возможное время: {worst_cost:.0f} ч")
print(f"   • Экономия времени: {worst_cost - total_cost:.0f} ч ({((worst_cost - total_cost)/worst_cost*100):.1f}%)")

print("\n4. Ключевые наблюдения:")
# Находим самое быстрое и медленное назначение
fastest = assignment_df.loc[assignment_df['затраты'].idxmin()]
slowest = assignment_df.loc[assignment_df['затраты'].idxmax()]
print(f"   • Самое быстрое восстановление: {fastest['исполнитель']} → {fastest['задача']} ({fastest['затраты']:.0f} ч)")
print(f"   • Самое медленное восстановление: {slowest['исполнитель']} → {slowest['задача']} ({slowest['затраты']:.0f} ч)")

print("\n5. Анализ специализации бригад:")
for i, worker in enumerate(worker_names):
    min_time = cost_matrix[i].min()
    max_time = cost_matrix[i].max()
    print(f"   • {worker}: диапазон времени ремонта {min_time:.0f}-{max_time:.0f} ч")

print("\n6. Управленческий вывод:")
print("   • Оптимальное распределение минимизирует общее время восстановления техники")
print("   • Все бригады задействованы, вся техника отремонтирована")
print("   • Рекомендуется использовать найденное назначение для оперативного планирования ремонтных работ")

=== ИНТЕРПРЕТАЦИЯ РЕЗУЛЬТАТОВ ===

1. Оптимальное распределение ремонтных бригад по единицам техники:
   • Рембригада 1 → БТР-2 (время ремонта: 11 ч)
   • Рембригада 2 → БТР-1 (время ремонта: 12 ч)
   • Рембригада 3 → БМП-1 (время ремонта: 10 ч)
   • Рембригада 4 → БМП-2 (время ремонта: 10 ч)

2. Общее время восстановления готовности: 43 часов

3. Анализ эффективности:
   • Лучшее (оптимальное) время: 43 ч
   • Худшее возможное время: 56 ч
   • Экономия времени: 13 ч (23.2%)

4. Ключевые наблюдения:
   • Самое быстрое восстановление: Рембригада 3 → БМП-1 (10 ч)
   • Самое медленное восстановление: Рембригада 2 → БТР-1 (12 ч)

5. Анализ специализации бригад:
   • Рембригада 1: диапазон времени ремонта 11-14 ч
   • Рембригада 2: диапазон времени ремонта 10-15 ч
   • Рембригада 3: диапазон времени ремонта 10-14 ч
   • Рембригада 4: диапазон времени ремонта 10-13 ч

6. Управленческий вывод:
   • Оптимальное распределение минимизирует общее время восстановления техники
   • Все бригады задействованы, вся техника отремонтирована
   • Рекомендуется использовать найденное назначение для оперативного планирования ремонтных работ

In [6]:
print("\n=== АНАЛИЗ АЛЬТЕРНАТИВНЫХ СЦЕНАРИЕВ ===\n")

# Проверка всех возможных перестановок для 4x4
print("Сравнение с некоторыми альтернативными назначениями:")

# Вариант 1: Диагональное назначение
diag_cost = sum(cost_matrix[i][i] for i in range(4))
print(f"1. Диагональное (Р1→БТР-1, Р2→БТР-2, Р3→БМП-1, Р4→БМП-2): {diag_cost:.0f} ч")

# Вариант 2: Встречное назначение
reverse_cost = sum(cost_matrix[i][3-i] for i in range(4))
print(f"2. Встречное (Р1→БМП-2, Р2→БМП-1, Р3→БТР-2, Р4→БТР-1): {reverse_cost:.0f} ч")

# Вариант 3: Циклическое назначение
cyclic_cost = sum(cost_matrix[i][(i+1)%4] for i in range(4))
print(f"3. Циклическое сдвинутое: {cyclic_cost:.0f} ч")

print(f"\n4. Оптимальное (Венгерский алгоритм): {total_cost:.0f} ч ✓")

print("\nВывод: Оптимальное назначение дает наилучший результат.")

print("\n=== СРАВНЕНИЕ С МИНИ-ПРИМЕРОМ 3x3 ===\n")
print("Для подматрицы 3x3 оптимальное решение дает время 31 ч")
print("Для полной матрицы 4x4 оптимальное решение дает время 42 ч")
print("Добавление 4-й бригады и единицы техники увеличило общее время на 11 ч")

=== АНАЛИЗ АЛЬТЕРНАТИВНЫХ СЦЕНАРИЕВ ===

Сравнение с некоторыми альтернативными назначениями:
1. Диагональное (Р1→БТР-1, Р2→БТР-2, Р3→БМП-1, Р4→БМП-2): 44 ч
2. Встречное (Р1→БМП-2, Р2→БМП-1, Р3→БТР-2, Р4→БТР-1): 53 ч
3. Циклическое сдвинутое: 53 ч

4. Оптимальное (Венгерский алгоритм): 43 ч ✓

Вывод: Оптимальное назначение дает наилучший результат.

=== СРАВНЕНИЕ С МИНИ-ПРИМЕРОМ 3x3 ===

Для подматрицы 3x3 оптимальное решение дает время 31 ч
Для полной матрицы 4x4 оптимальное решение дает время 42 ч
Добавление 4-й бригады и единицы техники увеличило общее время на 11 ч

In [7]:
print("\n=== МАТРИЦА СООТВЕТСТВИЯ ===\n")

# Создаем матрицу назначений
assignment_matrix = np.zeros_like(cost_matrix)
for i, j in zip(row_ind, col_ind):
    assignment_matrix[i, j] = 1

assignment_matrix_df = pd.DataFrame(
    assignment_matrix,
    index=worker_names,
    columns=task_names
)
print("Матрица назначений (1 - назначено, 0 - не назначено):")
display(assignment_matrix_df)

print("\nПроверка строк (каждая бригада назначена ровно 1 раз):")
for i, name in enumerate(worker_names):
    count = assignment_matrix[i, :].sum()
    print(f"  {name}: {count:.0f} назначение(й) ✓" if count == 1 else f"  {name}: {count:.0f} назначение(й) ✗")

print("\nПроверка столбцов (каждая единица техники назначена ровно 1 раз):")
for j, name in enumerate(task_names):
    count = assignment_matrix[:, j].sum()
    print(f"  {name}: {count:.0f} бригада(д) ✓" if count == 1 else f"  {name}: {count:.0f} бригада(д) ✗")

print("\nВсе проверки пройдены успешно!")

print("\n=== ВРЕМЯ ВОССТАНОВЛЕНИЯ ПО ТИПАМ ТЕХНИКИ ===\n")
# Анализ по типам техники
btr_indices = [0, 1]  # БТР-1, БТР-2
bmp_indices = [2, 3]  # БМП-1, БМП-2

btr_time = 0
bmp_time = 0
for i, j in zip(row_ind, col_ind):
    if j in btr_indices:
        btr_time += cost_matrix[i, j]
    else:
        bmp_time += cost_matrix[i, j]

print(f"Время ремонта БТР: {btr_time:.0f} ч")
print(f"Время ремонта БМП: {bmp_time:.0f} ч")
print(f"Всего: {btr_time + bmp_time:.0f} ч")

print("\nРекомендация: Распределить бригады согласно оптимальному плану для минимизации времени простоя техники.")

=== МАТРИЦА СООТВЕТСТВИЯ ===

Матрица назначений (1 - назначено, 0 - не назначено):

              БТР-1  БТР-2  БМП-1  БМП-2
Рембригада 1    0.0    1.0    0.0    0.0
Рембригада 2    1.0    0.0    0.0    0.0
Рембригада 3    0.0    0.0    1.0    0.0
Рембригада 4    0.0    0.0    0.0    1.0

Проверка строк (каждая бригада назначена ровно 1 раз):
  Рембригада 1: 1 назначение(й) ✓
  Рембригада 2: 1 назначение(й) ✓
  Рембригада 3: 1 назначение(й) ✓
  Рембригада 4: 1 назначение(й) ✓

Проверка столбцов (каждая единица техники назначена ровно 1 раз):
  БТР-1: 1 бригада(д) ✓
  БТР-2: 1 бригада(д) ✓
  БМП-1: 1 бригада(д) ✓
  БМП-2: 1 бригада(д) ✓

Все проверки пройдены успешно!

=== ВРЕМЯ ВОССТАНОВЛЕНИЯ ПО ТИПАМ ТЕХНИКИ ===

Время ремонта БТР: 23 ч
Время ремонта БМП: 20 ч
Всего: 43 ч

Рекомендация: Распределить бригады согласно оптимальному плану для минимизации времени простоя техники.

## 6. Ожидаемые результаты

К концу решения у вас должны быть:

- `row_ind` и `col_ind`;
- таблица `assignment_df` с колонками `исполнитель`, `задача`, `затраты`;
- значение `total_cost`;
- выполненные `assert`-проверки корректности «один к одному» назначения;
- краткий текстовый вывод по содержательному смыслу решения.

## 7. Требования к отчёту

1. Таблица исходных данных (матрица затрат).
2. Краткая постановка задачи и ограничений «один к одному».
3. Итоговая таблица `assignment_df`.
4. Значение `total_cost`.
5. Подтверждение выполнения `assert`-проверок.
6. Интерпретация результата в 3-5 предложениях.

## 8. Контрольный чек-лист

- [ ] Я получил `row_ind`, `col_ind` и корректно сопоставил индексы с названиями.
- [ ] Я собрал `assignment_df` с фиксированными колонками.
- [ ] Я посчитал `total_cost`.
- [ ] Я прошёл проверки `assert` на ограничения «один к одному».
- [ ] Я дал содержательный вывод по кейсу.