# ЛР-04: Преподаватели по учебным группам

## Student notebook: civil 02

Это рабочая тетрадь студента для самостоятельного решения.

Готовых численных ответов здесь нет: вы проходите весь учебный маршрут и фиксируете результаты по шагам.

## 1. Контекст и цель

Учебная часть распределяет преподавателей по группам. Матрица отражает штраф за неудобное расписание и профильную несовместимость.

Цель: получить корректное взаимно-однозначное назначение с минимальным суммарным критерием.

## 2. Исходные данные

Критерий оптимизации: **интегральный штраф расписания** (минимизация).

| Исполнитель \ Задача | Группа А | Группа Б | Группа В | Группа Г |
| --- | --- | --- | --- | --- |
| Преподаватель 1 | 9 | 4 | 7 | 6 |
| Преподаватель 2 | 6 | 8 | 5 | 7 |
| Преподаватель 3 | 5 | 7 | 6 | 4 |
| Преподаватель 4 | 8 | 6 | 9 | 5 |

## 3. Мини-пример 3x3 вручную

Перед запуском метод решения сделайте короткую ручную проверку на подматрице 3x3.

| Исполнитель \ Задача | Группа А | Группа Б | Группа В |
| --- | --- | --- | --- |
| Преподаватель 1 | 9 | 4 | 7 |
| Преподаватель 2 | 6 | 8 | 5 |
| Преподаватель 3 | 5 | 7 | 6 |

Что сделать:
1. Предложите вручную взаимно-однозначное назначение для 3 исполнителей и 3 задач.
2. Посчитайте суммарный критерий вручную.
3. Сравните с результатом метод решения после выполнения кода.

## 4. Пошаговое задание

1. Подготовьте входные данные (`worker_names`, `task_names`, `cost_matrix`).
2. Решите задачу через `linear_sum_assignment`.
3. Соберите таблицу `assignment_df` с колонками `исполнитель`, `задача`, `затраты`.
4. Посчитайте `total_cost`.
5. Проверьте «один к одному» ограничения через `assert`.
6. Дайте короткую интерпретацию результата в прикладных терминах.

In [1]:
import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment

worker_names = ['Преподаватель 1', 'Преподаватель 2', 'Преподаватель 3', 'Преподаватель 4']
task_names = ['Группа А', 'Группа Б', 'Группа В', 'Группа Г']
cost_matrix = np.array([[9, 4, 7, 6], [6, 8, 5, 7], [5, 7, 6, 4], [8, 6, 9, 5]], dtype=float)

print('Размер матрицы:', cost_matrix.shape)
print('Исполнителей:', len(worker_names))
print('Задач:', len(task_names))

Размер матрицы: (4, 4)
Исполнителей: 4
Задач: 4

## 5. Шаблон самостоятельного решения

Заполните блоки с пометкой «Задание». После заполнения код должен вывести итоговую таблицу и пройти проверки `assert`.

In [2]:
# Задание 1: получите оптимальное назначение методом Венгера.
row_ind, col_ind = linear_sum_assignment(cost_matrix)

# Задание 2: вычислите суммарный критерий.
total_cost = float(cost_matrix[row_ind, col_ind].sum())

# Задание 3: соберите таблицу assignment_df с фиксированными колонками.
assignment_rows = []
for i, j in zip(row_ind, col_ind):
    assignment_rows.append({
        'исполнитель': worker_names[i],
        'задача': task_names[j],
        'затраты': float(cost_matrix[i, j]),
    })
assignment_df = pd.DataFrame(assignment_rows, columns=['исполнитель', 'задача', 'затраты'])

# Задание 4: включите проверки «один к одному» ограничений.
assert len(row_ind) == len(worker_names), 'Назначены не все исполнители.'
assert len(col_ind) == len(task_names), 'Назначены не все задачи.'
assert len(set(row_ind)) == len(worker_names), 'Исполнитель повторяется более одного раза.'
assert len(set(col_ind)) == len(task_names), 'Задача назначена более одного раза.'
assert assignment_df['исполнитель'].nunique() == len(worker_names), 'Дубликаты исполнителей в таблице.'
assert assignment_df['задача'].nunique() == len(task_names), 'Дубликаты задач в таблице.'

print("\n=== ОПТИМАЛЬНОЕ НАЗНАЧЕНИЕ ===\n")
display(assignment_df)
print('Суммарный критерий (общий штраф расписания):', total_cost)

print("\n=== ПРОВЕРКА ОГРАНИЧЕНИЙ ===\n")
print("✓ Все преподаватели назначены")
print("✓ Все группы распределены")
print("✓ Нет повторяющихся назначений")
print("✓ Взаимно-однозначное соответствие соблюдено")

=== ОПТИМАЛЬНОЕ НАЗНАЧЕНИЕ ===

       исполнитель    задача  затраты
0  Преподаватель 1  Группа Б      4.0
1  Преподаватель 2  Группа В      5.0
2  Преподаватель 3  Группа А      5.0
3  Преподаватель 4  Группа Г      5.0

Суммарный критерий (общий штраф расписания): 19.0

=== ПРОВЕРКА ОГРАНИЧЕНИЙ ===

✓ Все преподаватели назначены
✓ Все группы распределены
✓ Нет повторяющихся назначений
✓ Взаимно-однозначное соответствие соблюдено

In [3]:
print("\n=== ДЕТАЛЬНЫЙ АНАЛИЗ НАЗНАЧЕНИЙ ===\n")

# Сортируем назначения по штрафу
assignment_sorted = assignment_df.sort_values('затраты')
print("Назначения по возрастанию штрафа:")
display(assignment_sorted)

print("\nСтатистика по назначениям:")
print(f"Минимальный штраф: {assignment_sorted['затраты'].min():.0f}")
print(f"Максимальный штраф: {assignment_sorted['затраты'].max():.0f}")
print(f"Средний штраф: {assignment_sorted['затраты'].mean():.2f}")
print(f"Общий штраф: {assignment_sorted['затраты'].sum():.0f}")

print("\nСравнение с альтернативными вариантами:")
# Альтернативное назначение (диагональное)
alternative_cost = sum(cost_matrix[i][i] for i in range(4))
print(f"Диагональное назначение: {alternative_cost:.0f}")
print(f"Оптимальное назначение: {total_cost:.0f}")
print(f"Экономия штрафа: {alternative_cost - total_cost:.0f} ({((alternative_cost - total_cost)/alternative_cost*100):.1f}%)")

=== ДЕТАЛЬНЫЙ АНАЛИЗ НАЗНАЧЕНИЙ ===

Назначения по возрастанию штрафа:

       исполнитель    задача  затраты
0  Преподаватель 1  Группа Б      4.0
1  Преподаватель 2  Группа В      5.0
2  Преподаватель 3  Группа А      5.0
3  Преподаватель 4  Группа Г      5.0

Статистика по назначениям:
Минимальный штраф: 4
Максимальный штраф: 5
Средний штраф: 4.75
Общий штраф: 19

Сравнение с альтернативными вариантами:
Диагональное назначение: 28
Оптимальное назначение: 19
Экономия штрафа: 9 (32.1%)

In [4]:
print("\n=== МИНИ-ПРИМЕР 3x3 (РУЧНАЯ ПРОВЕРКА) ===\n")

# Подматрица 3x3
mini_workers = ['Преподаватель 1', 'Преподаватель 2', 'Преподаватель 3']
mini_tasks = ['Группа А', 'Группа Б', 'Группа В']
mini_cost = np.array([
    [9, 4, 7],
    [6, 8, 5],
    [5, 7, 6]
], dtype=float)

print("Матрица штрафов 3x3:")
mini_cost_df = pd.DataFrame(mini_cost, index=mini_workers, columns=mini_tasks)
display(mini_cost_df)

# Ручное решение для 3x3
print("\nРучной анализ возможных назначений:")
print("\nВариант 1: Преподаватель 1→Группа Б (4), Преподаватель 2→Группа А (6), Преподаватель 3→Группа В (6)")
cost1 = 4 + 6 + 6
print(f"  Суммарный штраф: {cost1}")

print("\nВариант 2: Преподаватель 1→Группа А (9), Преподаватель 2→Группа В (5), Преподаватель 3→Группа Б (7)")
cost2 = 9 + 5 + 7
print(f"  Суммарный штраф: {cost2}")

print("\nВариант 3: Преподаватель 1→Группа Б (4), Преподаватель 2→Группа В (5), Преподаватель 3→Группа А (5)")
cost3 = 4 + 5 + 5
print(f"  Суммарный штраф: {cost3}")

print("\nВариант 4: Преподаватель 1→Группа В (7), Преподаватель 2→Группа А (6), Преподаватель 3→Группа Б (7)")
cost4 = 7 + 6 + 7
print(f"  Суммарный штраф: {cost4}")

# Оптимальное решение для 3x3 через Венгерский алгоритм
mini_row, mini_col = linear_sum_assignment(mini_cost)
mini_cost_opt = mini_cost[mini_row, mini_col].sum()

print(f"\nОптимальное решение (Венгерский алгоритм): {mini_cost_opt:.0f}")
print(f"Минимальный найденный вручную: {min(cost1, cost2, cost3, cost4)}")

# Сравнение
if mini_cost_opt == min(cost1, cost2, cost3, cost4):
    print("✓ Ручная проверка подтверждает оптимальность!")
else:
    print("⚠ Ручной расчет требует уточнения")

print("\nОптимальное назначение для 3x3:")
mini_assignments = []
for i, j in zip(mini_row, mini_col):
    mini_assignments.append({
        'исполнитель': mini_workers[i],
        'задача': mini_tasks[j],
        'затраты': float(mini_cost[i, j])
    })
mini_df = pd.DataFrame(mini_assignments)
display(mini_df)

=== МИНИ-ПРИМЕР 3x3 (РУЧНАЯ ПРОВЕРКА) ===

Матрица штрафов 3x3:

                 Группа А  Группа Б  Группа В
Преподаватель 1       9.0       4.0       7.0
Преподаватель 2       6.0       8.0       5.0
Преподаватель 3       5.0       7.0       6.0

Ручной анализ возможных назначений:

Вариант 1: Преподаватель 1→Группа Б (4), Преподаватель 2→Группа А (6), Преподаватель 3→Группа В (6)
  Суммарный штраф: 16

Вариант 2: Преподаватель 1→Группа А (9), Преподаватель 2→Группа В (5), Преподаватель 3→Группа Б (7)
  Суммарный штраф: 21

Вариант 3: Преподаватель 1→Группа Б (4), Преподаватель 2→Группа В (5), Преподаватель 3→Группа А (5)
  Суммарный штраф: 14

Вариант 4: Преподаватель 1→Группа В (7), Преподаватель 2→Группа А (6), Преподаватель 3→Группа Б (7)
  Суммарный штраф: 20

Оптимальное решение (Венгерский алгоритм): 14
Минимальный найденный вручную: 14
✓ Ручная проверка подтверждает оптимальность!

Оптимальное назначение для 3x3:

       исполнитель    задача  затраты
0  Преподаватель 1  Группа Б      4.0
1  Преподаватель 2  Группа В      5.0
2  Преподаватель 3  Группа А      5.0

In [5]:
print("\n=== ИНТЕРПРЕТАЦИЯ РЕЗУЛЬТАТОВ ===\n")

print("1. Оптимальное распределение преподавателей по группам:")
for _, row in assignment_df.iterrows():
    print(f"   • {row['исполнитель']} → {row['задача']} (штраф: {row['затраты']:.0f})")

print(f"\n2. Общий штраф расписания: {total_cost:.0f}")

print("\n3. Анализ эффективности:")
# Сравниваем с худшим возможным назначением
worst_cost = 0
for i in range(4):
    worst_cost += max(cost_matrix[i])
print(f"   • Лучший (оптимальный) штраф: {total_cost:.0f}")
print(f"   • Худший возможный штраф: {worst_cost:.0f}")
print(f"   • Экономия штрафа: {worst_cost - total_cost:.0f} ({((worst_cost - total_cost)/worst_cost*100):.1f}%)")

print("\n4. Ключевые наблюдения:")
# Находим самое выгодное и невыгодное назначение
best = assignment_df.loc[assignment_df['затраты'].idxmin()]
worst = assignment_df.loc[assignment_df['затраты'].idxmax()]
print(f"   • Самое выгодное назначение: {best['исполнитель']} → {best['задача']} (штраф: {best['затраты']:.0f})")
print(f"   • Самое невыгодное назначение: {worst['исполнитель']} → {worst['задача']} (штраф: {worst['затраты']:.0f})")

print("\n5. Управленческий вывод:")
print("   • Оптимальное распределение минимизирует общий штраф расписания")
print("   • Все преподаватели задействованы, все группы обеспечены")
print("   • Рекомендуется использовать найденное назначение для составления расписания")

=== ИНТЕРПРЕТАЦИЯ РЕЗУЛЬТАТОВ ===

1. Оптимальное распределение преподавателей по группам:
   • Преподаватель 1 → Группа Б (штраф: 4)
   • Преподаватель 2 → Группа В (штраф: 5)
   • Преподаватель 3 → Группа А (штраф: 5)
   • Преподаватель 4 → Группа Г (штраф: 5)

2. Общий штраф расписания: 19

3. Анализ эффективности:
   • Лучший (оптимальный) штраф: 19
   • Худший возможный штраф: 33
   • Экономия штрафа: 14 (42.4%)

4. Ключевые наблюдения:
   • Самое выгодное назначение: Преподаватель 1 → Группа Б (штраф: 4)
   • Самое невыгодное назначение: Преподаватель 2 → Группа В (штраф: 5)

5. Управленческий вывод:
   • Оптимальное распределение минимизирует общий штраф расписания
   • Все преподаватели задействованы, все группы обеспечены
   • Рекомендуется использовать найденное назначение для составления расписания

In [6]:
print("\n=== МАТРИЦА СООТВЕТСТВИЯ ===\n")

# Создаем матрицу назначений
assignment_matrix = np.zeros_like(cost_matrix)
for i, j in zip(row_ind, col_ind):
    assignment_matrix[i, j] = 1

assignment_matrix_df = pd.DataFrame(
    assignment_matrix,
    index=worker_names,
    columns=task_names
)
print("Матрица назначений (1 - назначено, 0 - не назначено):")
display(assignment_matrix_df)

print("\nПроверка строк (каждый преподаватель назначен ровно 1 раз):")
for i, name in enumerate(worker_names):
    count = assignment_matrix[i, :].sum()
    print(f"  {name}: {count:.0f} назначение(й) ✓" if count == 1 else f"  {name}: {count:.0f} назначение(й) ✗")

print("\nПроверка столбцов (каждая группа назначена ровно 1 раз):")
for j, name in enumerate(task_names):
    count = assignment_matrix[:, j].sum()
    print(f"  {name}: {count:.0f} преподаватель(ей) ✓" if count == 1 else f"  {name}: {count:.0f} преподаватель(ей) ✗")

print("\nВсе проверки пройдены успешно!")

=== МАТРИЦА СООТВЕТСТВИЯ ===

Матрица назначений (1 - назначено, 0 - не назначено):

                 Группа А  Группа Б  Группа В  Группа Г
Преподаватель 1       0.0       1.0       0.0       0.0
Преподаватель 2       0.0       0.0       1.0       0.0
Преподаватель 3       1.0       0.0       0.0       0.0
Преподаватель 4       0.0       0.0       0.0       1.0

Проверка строк (каждый преподаватель назначен ровно 1 раз):
  Преподаватель 1: 1 назначение(й) ✓
  Преподаватель 2: 1 назначение(й) ✓
  Преподаватель 3: 1 назначение(й) ✓
  Преподаватель 4: 1 назначение(й) ✓

Проверка столбцов (каждая группа назначена ровно 1 раз):
  Группа А: 1 преподаватель(ей) ✓
  Группа Б: 1 преподаватель(ей) ✓
  Группа В: 1 преподаватель(ей) ✓
  Группа Г: 1 преподаватель(ей) ✓

Все проверки пройдены успешно!

## 6. Ожидаемые результаты

К концу решения у вас должны быть:

- `row_ind` и `col_ind`;
- таблица `assignment_df` с колонками `исполнитель`, `задача`, `затраты`;
- значение `total_cost`;
- выполненные `assert`-проверки корректности «один к одному» назначения;
- краткий текстовый вывод по содержательному смыслу решения.

## 7. Требования к отчёту

1. Таблица исходных данных (матрица затрат).
2. Краткая постановка задачи и ограничений «один к одному».
3. Итоговая таблица `assignment_df`.
4. Значение `total_cost`.
5. Подтверждение выполнения `assert`-проверок.
6. Интерпретация результата в 3-5 предложениях.

## 8. Контрольный чек-лист

- [ ] Я получил `row_ind`, `col_ind` и корректно сопоставил индексы с названиями.
- [ ] Я собрал `assignment_df` с фиксированными колонками.
- [ ] Я посчитал `total_cost`.
- [ ] Я прошёл проверки `assert` на ограничения «один к одному».
- [ ] Я дал содержательный вывод по кейсу.