# ЛР-04: Выездные бригады по районам

## Student notebook: civil 01

Это рабочая тетрадь студента для самостоятельного решения.

Готовых численных ответов здесь нет: вы проходите весь учебный маршрут и фиксируете результаты по шагам.

## 1. Контекст и цель

Муниципальный штаб должен назначить 4 выездные бригады на 4 района так, чтобы минимизировать время прибытия.

Цель: получить корректное взаимно-однозначное назначение с минимальным суммарным критерием.

## 2. Исходные данные

Критерий оптимизации: **время прибытия, мин** (минимизация).

| Исполнитель \ Задача | Северный район | Южный район | Западный район | Центральный район |
| --- | --- | --- | --- | --- |
| Бригада А | 32 | 18 | 27 | 21 |
| Бригада Б | 25 | 20 | 24 | 19 |
| Бригада В | 17 | 26 | 22 | 23 |
| Бригада Г | 24 | 19 | 18 | 20 |

## 3. Мини-пример 3x3 вручную

Перед запуском метод решения сделайте короткую ручную проверку на подматрице 3x3.

| Исполнитель \ Задача | Северный район | Южный район | Западный район |
| --- | --- | --- | --- |
| Бригада А | 32 | 18 | 27 |
| Бригада Б | 25 | 20 | 24 |
| Бригада В | 17 | 26 | 22 |

Что сделать:
1. Предложите вручную взаимно-однозначное назначение для 3 исполнителей и 3 задач.
2. Посчитайте суммарный критерий вручную.
3. Сравните с результатом метод решения после выполнения кода.

## 4. Пошаговое задание

1. Подготовьте входные данные (`worker_names`, `task_names`, `cost_matrix`).
2. Решите задачу через `linear_sum_assignment`.
3. Соберите таблицу `assignment_df` с колонками `исполнитель`, `задача`, `затраты`.
4. Посчитайте `total_cost`.
5. Проверьте «один к одному» ограничения через `assert`.
6. Дайте короткую интерпретацию результата в прикладных терминах.

In [1]:
import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment

worker_names = ['Бригада А', 'Бригада Б', 'Бригада В', 'Бригада Г']
task_names = ['Северный район', 'Южный район', 'Западный район', 'Центральный район']
cost_matrix = np.array([[32, 18, 27, 21], [25, 20, 24, 19], [17, 26, 22, 23], [24, 19, 18, 20]], dtype=float)

print('Размер матрицы:', cost_matrix.shape)
print('Исполнителей:', len(worker_names))
print('Задач:', len(task_names))

Размер матрицы: (4, 4)
Исполнителей: 4
Задач: 4

## 5. Шаблон самостоятельного решения

Заполните блоки с пометкой «Задание». После заполнения код должен вывести итоговую таблицу и пройти проверки `assert`.

In [2]:
# Задание 1: получите оптимальное назначение методом Венгера.
row_ind, col_ind = linear_sum_assignment(cost_matrix)

# Задание 2: вычислите суммарный критерий.
total_cost = float(cost_matrix[row_ind, col_ind].sum())

# Задание 3: соберите таблицу assignment_df с фиксированными колонками.
assignment_rows = []
for i, j in zip(row_ind, col_ind):
    assignment_rows.append({
        'исполнитель': worker_names[i],
        'задача': task_names[j],
        'затраты': float(cost_matrix[i, j]),
    })
assignment_df = pd.DataFrame(assignment_rows, columns=['исполнитель', 'задача', 'затраты'])

# Задание 4: включите проверки «один к одному» ограничений.
assert len(row_ind) == len(worker_names), 'Назначены не все исполнители.'
assert len(col_ind) == len(task_names), 'Назначены не все задачи.'
assert len(set(row_ind)) == len(worker_names), 'Исполнитель повторяется более одного раза.'
assert len(set(col_ind)) == len(task_names), 'Задача назначена более одного раза.'
assert assignment_df['исполнитель'].nunique() == len(worker_names), 'Дубликаты исполнителей в таблице.'
assert assignment_df['задача'].nunique() == len(task_names), 'Дубликаты задач в таблице.'

print("\n=== ОПТИМАЛЬНОЕ НАЗНАЧЕНИЕ ===\n")
display(assignment_df)
print('Суммарный критерий (общее время прибытия):', total_cost, 'минут')

print("\n=== ПРОВЕРКА ОГРАНИЧЕНИЙ ===\n")
print("✓ Все исполнители назначены")
print("✓ Все задачи распределены")
print("✓ Нет повторяющихся назначений")
print("✓ Взаимно-однозначное соответствие соблюдено")

=== ОПТИМАЛЬНОЕ НАЗНАЧЕНИЕ ===

  исполнитель             задача  затраты
0   Бригада А        Южный район     18.0
1   Бригада Б  Центральный район     19.0
2   Бригада В     Северный район     17.0
3   Бригада Г     Западный район     18.0

Суммарный критерий (общее время прибытия): 72.0 минут

=== ПРОВЕРКА ОГРАНИЧЕНИЙ ===

✓ Все исполнители назначены
✓ Все задачи распределены
✓ Нет повторяющихся назначений
✓ Взаимно-однозначное соответствие соблюдено

In [4]:
print("\n=== ДЕТАЛЬНЫЙ АНАЛИЗ НАЗНАЧЕНИЙ ===\n")

# Сортируем назначения по времени
assignment_sorted = assignment_df.sort_values('затраты')
print("Назначения по возрастанию времени прибытия:")
display(assignment_sorted)

print("\nСтатистика по назначениям:")
print(f"Минимальное время прибытия: {assignment_sorted['затраты'].min():.0f} мин")
print(f"Максимальное время прибытия: {assignment_sorted['затраты'].max():.0f} мин")
print(f"Среднее время прибытия: {assignment_sorted['затраты'].mean():.2f} мин")
print(f"Общее время прибытия: {assignment_sorted['затраты'].sum():.0f} мин")

print("\nСравнение с альтернативными вариантами:")
# Альтернативное назначение (диагональное)
alternative_cost = sum(cost_matrix[i][i] for i in range(4))
print(f"Диагональное назначение: {alternative_cost:.0f} мин")
print(f"Оптимальное назначение: {total_cost:.0f} мин")
print(f"Экономия: {alternative_cost - total_cost:.0f} мин ({((alternative_cost - total_cost)/alternative_cost*100):.1f}%)")

=== ДЕТАЛЬНЫЙ АНАЛИЗ НАЗНАЧЕНИЙ ===

Назначения по возрастанию времени прибытия:

  исполнитель             задача  затраты
2   Бригада В     Северный район     17.0
0   Бригада А        Южный район     18.0
3   Бригада Г     Западный район     18.0
1   Бригада Б  Центральный район     19.0

Статистика по назначениям:
Минимальное время прибытия: 17 мин
Максимальное время прибытия: 19 мин
Среднее время прибытия: 18.00 мин
Общее время прибытия: 72 мин

Сравнение с альтернативными вариантами:
Диагональное назначение: 94 мин
Оптимальное назначение: 72 мин
Экономия: 22 мин (23.4%)

In [5]:
print("\n МИНИ-ПРИМЕР 3x3 (РУЧНАЯ ПРОВЕРКА) \n")

# Подматрица 3x3
mini_workers = ['Бригада А', 'Бригада Б', 'Бригада В']
mini_tasks = ['Северный район', 'Южный район', 'Западный район']
mini_cost = np.array([
    [32, 18, 27],
    [25, 20, 24],
    [17, 26, 22]
], dtype=float)

print("Матрица затрат 3x3:")
mini_cost_df = pd.DataFrame(mini_cost, index=mini_workers, columns=mini_tasks)
display(mini_cost_df)

# Ручное решение для 3x3
print("\nРучной анализ возможных назначений:")
print("\nВариант 1: Бригада А→Южный (18), Бригада Б→Северный (25), Бригада В→Западный (22)")
cost1 = 18 + 25 + 22
print(f"  Суммарное время: {cost1} мин")

print("\nВариант 2: Бригада А→Северный (32), Бригада Б→Южный (20), Бригада В→Западный (22)")
cost2 = 32 + 20 + 22
print(f"  Суммарное время: {cost2} мин")

print("\nВариант 3: Бригада А→Южный (18), Бригада Б→Западный (24), Бригада В→Северный (17)")
cost3 = 18 + 24 + 17
print(f"  Суммарное время: {cost3} мин")

print("\nВариант 4: Бригада А→Западный (27), Бригада Б→Северный (25), Бригада В→Южный (26)")
cost4 = 27 + 25 + 26
print(f"  Суммарное время: {cost4} мин")

# Оптимальное решение для 3x3 через Венгерский алгоритм
mini_row, mini_col = linear_sum_assignment(mini_cost)
mini_cost_opt = mini_cost[mini_row, mini_col].sum()

print(f"\nОптимальное решение (Венгерский алгоритм): {mini_cost_opt:.0f} мин")
print(f"Минимальное найденное вручную: {min(cost1, cost2, cost3, cost4)} мин")

# Сравнение
if mini_cost_opt == min(cost1, cost2, cost3, cost4):
    print("✓ Ручная проверка подтверждает оптимальность!")
else:
    print("⚠ Ручной расчет требует уточнения")

print("\nОптимальное назначение для 3x3:")
mini_assignments = []
for i, j in zip(mini_row, mini_col):
    mini_assignments.append({
        'исполнитель': mini_workers[i],
        'задача': mini_tasks[j],
        'затраты': float(mini_cost[i, j])
    })
mini_df = pd.DataFrame(mini_assignments)
display(mini_df)

 МИНИ-ПРИМЕР 3x3 (РУЧНАЯ ПРОВЕРКА)

Матрица затрат 3x3:

           Северный район  Южный район  Западный район
Бригада А            32.0         18.0            27.0
Бригада Б            25.0         20.0            24.0
Бригада В            17.0         26.0            22.0

Ручной анализ возможных назначений:

Вариант 1: Бригада А→Южный (18), Бригада Б→Северный (25), Бригада В→Западный (22)
  Суммарное время: 65 мин

Вариант 2: Бригада А→Северный (32), Бригада Б→Южный (20), Бригада В→Западный (22)
  Суммарное время: 74 мин

Вариант 3: Бригада А→Южный (18), Бригада Б→Западный (24), Бригада В→Северный (17)
  Суммарное время: 59 мин

Вариант 4: Бригада А→Западный (27), Бригада Б→Северный (25), Бригада В→Южный (26)
  Суммарное время: 78 мин

Оптимальное решение (Венгерский алгоритм): 59 мин
Минимальное найденное вручную: 59 мин
✓ Ручная проверка подтверждает оптимальность!

Оптимальное назначение для 3x3:

  исполнитель          задача  затраты
0   Бригада А     Южный район     18.0
1   Бригада Б  Западный район     24.0
2   Бригада В  Северный район     17.0

In [6]:
print("\n=== ИНТЕРПРЕТАЦИЯ РЕЗУЛЬТАТОВ ===\n")

print("1. Оптимальное распределение бригад по районам:")
for _, row in assignment_df.iterrows():
    print(f"   • {row['исполнитель']} → {row['задача']} (время: {row['затраты']:.0f} мин)")

print(f"\n2. Общее время прибытия всех бригад: {total_cost:.0f} минут")

print("\n3. Анализ эффективности:")
# Сравниваем с худшим возможным назначением
worst_cost = 0
for i in range(4):
    worst_cost += max(cost_matrix[i])
print(f"   • Лучшее (оптимальное) время: {total_cost:.0f} мин")
print(f"   • Худшее возможное время: {worst_cost:.0f} мин")
print(f"   • Экономия времени: {worst_cost - total_cost:.0f} мин ({((worst_cost - total_cost)/worst_cost*100):.1f}%)")

print("\n4. Ключевые наблюдения:")
# Находим самое быстрое и медленное назначение
fastest = assignment_df.loc[assignment_df['затраты'].idxmin()]
slowest = assignment_df.loc[assignment_df['затраты'].idxmax()]
print(f"   • Самое быстрое назначение: {fastest['исполнитель']} → {fastest['задача']} ({fastest['затраты']:.0f} мин)")
print(f"   • Самое медленное назначение: {slowest['исполнитель']} → {slowest['задача']} ({slowest['затраты']:.0f} мин)")

print("\n5. Управленческий вывод:")
print("   • Оптимальное распределение позволяет минимизировать общее время прибытия")
print("   • Все бригады задействованы, все районы охвачены")
print("   • Рекомендуется использовать найденное назначение для оперативного планирования")

=== ИНТЕРПРЕТАЦИЯ РЕЗУЛЬТАТОВ ===

1. Оптимальное распределение бригад по районам:
   • Бригада А → Южный район (время: 18 мин)
   • Бригада Б → Центральный район (время: 19 мин)
   • Бригада В → Северный район (время: 17 мин)
   • Бригада Г → Западный район (время: 18 мин)

2. Общее время прибытия всех бригад: 72 минут

3. Анализ эффективности:
   • Лучшее (оптимальное) время: 72 мин
   • Худшее возможное время: 107 мин
   • Экономия времени: 35 мин (32.7%)

4. Ключевые наблюдения:
   • Самое быстрое назначение: Бригада В → Северный район (17 мин)
   • Самое медленное назначение: Бригада Б → Центральный район (19 мин)

5. Управленческий вывод:
   • Оптимальное распределение позволяет минимизировать общее время прибытия
   • Все бригады задействованы, все районы охвачены
   • Рекомендуется использовать найденное назначение для оперативного планирования

In [7]:
print("\n=== АНАЛИЗ АЛЬТЕРНАТИВНЫХ СЦЕНАРИЕВ ===\n")

# Проверка всех возможных перестановок для 4x4 (для демонстрации)
print("Сравнение с некоторыми альтернативными назначениями:")

# Вариант 1: Диагональное назначение
diag_cost = sum(cost_matrix[i][i] for i in range(4))
print(f"1. Диагональное (А→Сев, Б→Южн, В→Зап, Г→Центр): {diag_cost:.0f} мин")

# Вариант 2: Встречное назначение
reverse_cost = sum(cost_matrix[i][3-i] for i in range(4))
print(f"2. Встречное (А→Центр, Б→Зап, В→Южн, Г→Сев): {reverse_cost:.0f} мин")

# Вариант 3: Циклическое назначение
cyclic_cost = sum(cost_matrix[i][(i+1)%4] for i in range(4))
print(f"3. Циклическое сдвинутое: {cyclic_cost:.0f} мин")

print(f"\n4. Оптимальное (Венгерский алгоритм): {total_cost:.0f} мин ✓")

print("\nВывод: Оптимальное назначение дает наилучший результат.")

=== АНАЛИЗ АЛЬТЕРНАТИВНЫХ СЦЕНАРИЕВ ===

Сравнение с некоторыми альтернативными назначениями:
1. Диагональное (А→Сев, Б→Южн, В→Зап, Г→Центр): 94 мин
2. Встречное (А→Центр, Б→Зап, В→Южн, Г→Сев): 95 мин
3. Циклическое сдвинутое: 89 мин

4. Оптимальное (Венгерский алгоритм): 72 мин ✓

Вывод: Оптимальное назначение дает наилучший результат.

## 6. Ожидаемые результаты

К концу решения у вас должны быть:

- `row_ind` и `col_ind`;
- таблица `assignment_df` с колонками `исполнитель`, `задача`, `затраты`;
- значение `total_cost`;
- выполненные `assert`-проверки корректности «один к одному» назначения;
- краткий текстовый вывод по содержательному смыслу решения.

## 7. Требования к отчёту

1. Таблица исходных данных (матрица затрат).
2. Краткая постановка задачи и ограничений «один к одному».
3. Итоговая таблица `assignment_df`.
4. Значение `total_cost`.
5. Подтверждение выполнения `assert`-проверок.
6. Интерпретация результата в 3-5 предложениях.

## 8. Контрольный чек-лист

- [ ] Я получил `row_ind`, `col_ind` и корректно сопоставил индексы с названиями.
- [ ] Я собрал `assignment_df` с фиксированными колонками.
- [ ] Я посчитал `total_cost`.
- [ ] Я прошёл проверки `assert` на ограничения «один к одному».
- [ ] Я дал содержательный вывод по кейсу.